name: changelogPrint

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: changelogPrint
    steps:
      - uses: actions/checkout@v3
      - name: jdk 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: gradle caching
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - run: ./gradlew changelogPrint
