# GH_TOKEN
# NEXUS_USER
# NEXUS_PASS64 (base64 NOTE: `base64` and `openssl base64` failed, had to use Java
#   byte[] data = "{{password}}".getBytes(StandardCharsets.UTF_8);
#   String encoded = new String(Base64.getEncoder().encode(data), StandardCharsets.UTF_8);
#   System.out.println(encoded);
# GPG_PASSPHRASE
# GPG_KEY64 (base64)
#   gpg --export-secret-keys --armor KEY_ID | openssl base64 | pbcopy
# GRADLE_KEY
# GRADLE_SECRET

name: deploy
on:
  workflow_dispatch:
    inputs:
      to_publish:
        description: 'What to publish'
        required: true
        default: 'all'
        type: choice
        options:
          - all

jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy
    env:
      gh_token: ${{ secrets.GH_TOKEN }}
      ORG_GRADLE_PROJECT_nexus_user: ${{ secrets.NEXUS_USER }}
      ORG_GRADLE_PROJECT_nexus_pass64: ${{ secrets.NEXUS_PASS64 }}
      ORG_GRADLE_PROJECT_gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      ORG_GRADLE_PROJECT_gpg_key64: ${{ secrets.GPG_KEY64 }}
    steps:
      - uses: actions/checkout@v3
      - name: jdk 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: gradle caching
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: git fetch origin main
        run: git fetch origin main
      - name: publish all
        if: "${{ github.event.inputs.to_publish == 'all' }}"
        run: |
          ./gradlew :changelogPush -Prelease=true -Penable_publishing=true -Pgradle.publish.key=${{ secrets.GRADLE_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }} --stacktrace --warning-mode all
